-- Histórico de cálculos. Idempotente: pode rodar quantas vezes for, em banco novo ou já migrado.

CREATE SCHEMA IF NOT EXISTS emolumentos;

CREATE TABLE IF NOT EXISTS emolumentos.calculos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_calculos PRIMARY KEY,
    criado_em       TIMESTAMP(3)   NOT NULL, -- UTC
    uf              CHAR(2)        NOT NULL,
    ato             VARCHAR(40)    NOT NULL,
    codigo_ato      VARCHAR(20)    NOT NULL,
    quantidade      INT            NOT NULL,
    valor_declarado NUMERIC(18, 2) NOT NULL,
    total           NUMERIC(18, 2) NOT NULL
);
